### ISSUE TITLE
Multiple TX likely does not work

### ISSUE THREAD

**Issue by eclab** [hexaedron/PostNeoSWSerial#3]
In the original NeoSWSerial, the tx mask was global and not changed on write, so if you had multiple serial ports open, regardless of which one you wrote to, only the last one would actually do the writing (out its port).  BAD.

A fix was proposed here:

https://github.com/SlashDevin/NeoSWSerial/pull/48/commits/e7dac29e6aabb997a948d92a7513df89a1b3fcfb#diff-772b9d7b744e2b968bde25fc1f7557adab240ef529b05de62e2ba78f97f6450d

Please consider including this in your version as well.

**Comment by hexaedron** [comment]
Looks like an easy fix. I'll take a look next week.

**Comment by hexaedron** [comment]
Fixed here: https://github.com/hexaedron/PostNeoSWSerial/releases/tag/1.0.5
